#![no_std]
#![no_main]

use defmt_semihosting as _;

#[aarch32_rt::entry]
fn main() -> ! {
    unsafe extern "C" {
        unsafe fn main() -> !;
    }
    defmt::info!("In entry point");
    unsafe {
        // this is the function generated by rtic
        main();
    }
}

#[rtic::app(device=mps3_an536, dispatchers=[SGI_1, SGI_2])]
mod app {
    use rtic_time::Monotonic;

    #[shared]
    struct SharedResources {}

    #[local]
    struct LocalResources {}

    #[init]
    fn init(mut ctx: init::Context) -> (SharedResources, LocalResources) {
        defmt::info!("In init...");

        // TODO: have RTIC configure the GIC with all the desired interrupts at the desired priorities
        const VIRT_TIMER_ID: rtic::export::IntId = mps3_an536::interrupt::VirtTimer.as_intid();
        ctx.core.gic.set_interrupt_priority(VIRT_TIMER_ID, 0x31);
        ctx.core.gic.enable_interrupt(VIRT_TIMER_ID, true);

        // TODO: have RTIC set the primask for us
        rtic::export::Gic::set_priority_mask(0xFF);

        mps3_an536::Mono::start(ctx.core.virt_timer);

        loop_500::spawn().unwrap();
        loop_2000::spawn().unwrap();

        (SharedResources {}, LocalResources {})
    }

    #[task]
    async fn loop_500(_ctx: loop_500::Context) -> ! {
        loop {
            defmt::info!("500 ms tick");
            mps3_an536::Mono::delay(mps3_an536::Duration::millis(500)).await;
        }
    }

    #[task]
    async fn loop_2000(_ctx: loop_2000::Context) -> ! {
        loop {
            defmt::info!("********* 2 second tick");
            mps3_an536::Mono::delay(mps3_an536::Duration::millis(2000)).await;
        }
    }

    // TODO: have RTIC generate this routine for us (or #[derive] it from the interrupt enum)
    #[aarch32_rt::irq]
    fn irq() {
        let handler = |int_id| {
            if mps3_an536::interrupt::VirtTimer == int_id {
                defmt::debug!("VirtTimer tick");
                mps3_an536::Mono::handle_irq();
            } else {
                panic!("Unexpected interrupt {:?}", int_id);
            }
        };
        defmt::debug!("> IRQ");
        unsafe {
            while rtic::export::get_and_process(handler) {
                // keep going
            }
        }
        defmt::debug!("< IRQ");
    }
}

defmt::timestamp!(
    "{:tus}",
    (aarch32_cpu::generic_timer::read_virtual_timer() * 2) / 125
);

#[panic_handler]
fn panic(info: &core::panic::PanicInfo) -> ! {
    defmt::error!("PANIC: {}", info);
    loop {
        aarch32_cpu::asm::wfe();
    }
}
