#![no_std]
#![no_main]

use defmt_semihosting as _;

#[aarch32_rt::entry]
fn main() -> ! {
    unsafe extern "C" {
        unsafe fn main() -> !;
    }
    defmt::println!("In entry point");
    unsafe {
        // this is the function generated by rtic
        main();
    }
}

#[rtic::app(device=mps3_an536, dispatchers=[SGI_1, SGI_2])]
mod app {
    const TICKS_PER_BEAT: u64 = 62_500_000;
    use aarch32_cpu::generic_timer::GenericTimer;

    #[shared]
    struct SharedResources {

    }

    #[local]
    struct LocalResources {
        timer: aarch32_cpu::generic_timer::El1VirtualTimer,
    }

    #[init]
    fn init(mut ctx: init::Context) -> (SharedResources, LocalResources) {      
        defmt::println!("In init...");

        // TODO: have rtic construct the GIC from a GICD_BASE: usize and a GICR_OFFSET: usize value passed in to the rtic::app macro
        let mut gic = unsafe { mps3_an536::make_gic() };

        // TODO: have RTIC configure the GIC with all the desired interrupts at the desired priorities
        let int_id: rtic::export::IntId = mps3_an536::interrupt::VIRT_TIMER.into();
        gic.set_interrupt_priority(int_id, Some(0), 0x31).unwrap();
        gic.set_group(int_id, Some(0), rtic::export::arm_gic::gicv3::Group::Group1NS).unwrap();
        gic.enable_interrupt(int_id, Some(0), true).unwrap();

        // TODO: have RTIC set the primask for us
        rtic::export::arm_gic::gicv3::GicCpuInterface::set_priority_mask(0xFF);

        ctx.core.timer.counter_compare_set(TICKS_PER_BEAT);
        ctx.core.timer.interrupt_mask(false);
        ctx.core.timer.enable(true);
        
        (SharedResources {}, LocalResources {
            timer: ctx.core.timer,
        })
    }

    #[idle()]
    fn idle(ctx: idle::Context) -> ! {
        let mut timer_alt = unsafe { aarch32_cpu::generic_timer::El1VirtualTimer::new() };

        loop {
            defmt::println!("In idle counter={}, status={}, masked={}, enabled={}", timer_alt.counter(), timer_alt.interrupt_status(), timer_alt.interrupt_masked(), timer_alt.enabled());
            let cpsr = aarch32_cpu::register::Cpsr::read();
            defmt::println!("{}", cpsr);
            for _ in 0..5_000_000 {
                aarch32_cpu::asm::nop();;
            }
            aarch32_cpu::asm::wfe();
        }
    }

    #[task(binds = VIRT_TIMER, local = [timer])]
    fn timer_tick(ctx: timer_tick::Context) {
        let last = ctx.local.timer.counter_compare();
        let next = last + TICKS_PER_BEAT;

        defmt::println!("TICK @ {}, next at {}, freq = {}", last, next, ctx.local.timer.frequency_hz());

        ctx.local.timer.counter_compare_set(next);

        defmt::println!("next at {}", ctx.local.timer.counter_compare());
    }

}

// TODO: have RTIC generate this routine for us (or #[derive] it from the interrupt enum)
#[aarch32_rt::irq]
fn irq() {
    use rtic::export::arm_gic::{InterruptGroup, gicv3::GicCpuInterface};
    defmt::info!("> IRQ");
    let cpsr = aarch32_cpu::register::Cpsr::read();
    defmt::info!("{}", cpsr);

    while let Some(int_id) = GicCpuInterface::get_and_acknowledge_interrupt(InterruptGroup::Group1)
    {
        if mps3_an536::interrupt::PHYS_TIMER == int_id {
            unsafe extern "C" {
                fn PHYS_TIMER();
            }
            unsafe {
                PHYS_TIMER();
            }
        } else if mps3_an536::interrupt::VIRT_TIMER == int_id {
            unsafe extern "C" {
                fn VIRT_TIMER();
            }
            unsafe {
                VIRT_TIMER();
            }
        } else {
            panic!("We handle all enabled IRQs");
        }
        GicCpuInterface::end_interrupt(int_id, InterruptGroup::Group1);
    }
    defmt::info!("< IRQ");
}

#[panic_handler]
fn panic(info: &core::panic::PanicInfo) -> ! {
    defmt::error!("PANIC: {}", info);
       loop {
        aarch32_cpu::asm::wfe();
    } 
}
